const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));
let schedules=[],mood='pop',selectedDate='',selectedTime='20:00',currentMonth=new Date(),currentDesign=null,compactLevel=0,brightness=0;
let illust={src:null,x:0,y:0,flip:false},drag=null,pickMode=false;
const patterns=['stars','hearts','dots','grid','stripe','check','waves','bubbles','hex','confetti','japan','none'];
const worlds={
 pop:{name:'ポップ',grad:['#4f7cff','#ff7ab6'],patterns:['confetti','dots','stars','stripe'],title:'Weekly Schedule',font:'rounded'},
 cool:{name:'クール',grad:['#0f172a','#38bdf8'],patterns:['grid','hex','stripe','none'],title:'STREAM PLAN',font:'gothic'},
 game:{name:'ゲーム',grad:['#111827','#22d3ee'],patterns:['hex','grid','stars','stripe'],title:'STREAM QUEST',font:'gothic'},
 minimal:{name:'ミニマル',grad:['#f8fafc','#94a3b8'],patterns:['none','grid','dots','stripe'],title:'Schedule',font:'simple'},
 cute:{name:'かわいい',grad:['#ff8cc6','#ffe6a7'],patterns:['hearts','dots','confetti','stars'],title:'今週の予定',font:'rounded'},
 neon:{name:'ネオン',grad:['#20002c','#00d4ff'],patterns:['grid','hex','stars','stripe'],title:'NEON WEEK',font:'gothic'},
 summer:{name:'夏',grad:['#00b4d8','#caf0f8'],patterns:['waves','bubbles','dots','stars'],title:'SUMMER LIVE',font:'rounded'},
 space:{name:'宇宙',grad:['#1d2671','#c33764'],patterns:['stars','grid','hex','dots'],title:'COSMIC SCHEDULE',font:'gothic'},
 cafe:{name:'カフェ',grad:['#7c4a2d','#f7d9b9'],patterns:['check','dots','stripe','none'],title:'Cafe Schedule',font:'simple'},
 japan:{name:'和風',grad:['#7f1d1d','#fbbf24'],patterns:['japan','waves','stripe','none'],title:'今週ノ予定',font:'serif'},
 mono:{name:'モノトーン',grad:['#111827','#9ca3af'],patterns:['grid','none','stripe','check'],title:'MONO SCHEDULE',font:'gothic'},
 retro:{name:'レトロ',grad:['#583101','#ffb703'],patterns:['check','dots','stripe','confetti'],title:'RETRO WEEK',font:'rounded'}
};
function init(){setDefaultDate();bind();renderCalendar();renderSchedules();generateCandidates(false)}
function bind(){
 $('#openCalendarBtn').onclick=()=>openModal('#calendarModal');$('#closeCalendar').onclick=()=>closeModal('#calendarModal');$('#prevMonth').onclick=()=>{currentMonth.setMonth(currentMonth.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{currentMonth.setMonth(currentMonth.getMonth()+1);renderCalendar()};
 $('#openTimeBtn').onclick=()=>{let [h,m]=selectedTime.split(':').map(Number);$('#hourRange').value=h;$('#minuteRange').value=Math.round(m/5);updateBigTime();openModal('#timeModal')};$('#hourRange').oninput=updateBigTime;$('#minuteRange').oninput=updateBigTime;$('#applyTime').onclick=()=>{selectedTime=$('#bigTime').textContent;$('#timeText').textContent=selectedTime;closeModal('#timeModal')};
 $('#addScheduleBtn').onclick=addSchedule;$('#generateBtn').onclick=generateWithLog;$('#shuffleBtn').onclick=()=>generateCandidates(true);$('#resetBtn').onclick=resetAll;
 $$('#moodChips .chip').forEach(b=>b.onclick=()=>{mood=b.dataset.mood;$$('#moodChips .chip').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
 $('#illustInput').onchange=loadIllust;$('#autoRemoveBgBtn').onclick=()=>autoRemoveBackground();$('#whiteRemoveBtn').onclick=()=>removeColor([255,255,255]);$('#pickColorBtn').onclick=()=>{pickMode=true;$('#aiLog').textContent='イラスト上の消したい背景色をクリックしてください。'};$('#flipBtn').onclick=()=>{illust.flip=!illust.flip;updateIllustStyle()};$('#deleteIllustBtn').onclick=()=>{illust={src:null,x:0,y:0,flip:false};$('#illust').style.display='none';$('#illustTools').classList.add('hidden')};
 $('#threshold').oninput=()=>{};$('#softness').oninput=()=>{};$('#illustSize').oninput=updateIllustStyle;$('#illustRotate').oninput=updateIllustStyle;
 $('#illust').addEventListener('pointerdown',e=>{if(pickMode){pickColorFromImage(e);return}drag={x:e.clientX,y:e.clientY,left:illust.x||0,top:illust.y||0};$('#illust').setPointerCapture(e.pointerId)});$('#illust').addEventListener('pointermove',e=>{if(!drag||!illust.src)return;illust.x=drag.left+(e.clientX-drag.x);illust.y=drag.top+(e.clientY-drag.y);updateIllustStyle()});$('#illust').addEventListener('pointerup',()=>drag=null);
 $('#nextPatternBtn').onclick=()=>{if(!currentDesign)return;let arr=worlds[currentDesign.key].patterns;let i=arr.indexOf(currentDesign.pattern);currentDesign.pattern=arr[(i+1)%arr.length];applyDesign(currentDesign)};$('#autoFitBtn').onclick=()=>{compactLevel=(compactLevel+1)%4;renderArt()};$('#brightBtn').onclick=()=>{brightness=Math.min(brightness+8,28);applyDesign(currentDesign)};$('#darkBtn').onclick=()=>{brightness=Math.max(brightness-8,-40);applyDesign(currentDesign)};$('#wmCheck').onchange=e=>$('#watermark').style.display=e.target.checked?'block':'none';$('#savePngBtn').onclick=savePng;
}
function setDefaultDate(){let d=new Date();selectedDate=d.toISOString().slice(0,10);$('#dateText').textContent=fmtDate(selectedDate)}
function openModal(s){$(s).classList.remove('hidden')}function closeModal(s){$(s).classList.add('hidden')}
function renderCalendar(){let y=currentMonth.getFullYear(),m=currentMonth.getMonth();$('#monthLabel').textContent=`${y}年 ${m+1}月`;let first=new Date(y,m,1),last=new Date(y,m+1,0),html='';for(let i=0;i<first.getDay();i++)html+='<button class="dayBtn empty" disabled></button>';for(let d=1;d<=last.getDate();d++){let val=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;html+=`<button class="dayBtn ${val===selectedDate?'selected':''}" data-date="${val}">${d}</button>`}$('#calendarGrid').innerHTML=html;$$('.dayBtn[data-date]').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.date;$('#dateText').textContent=fmtDate(selectedDate);renderCalendar();closeModal('#calendarModal')})}
function updateBigTime(){let h=String($('#hourRange').value).padStart(2,'0'),m=String(+$('#minuteRange').value*5).padStart(2,'0');$('#bigTime').textContent=`${h}:${m}`}
function addSchedule(){let title=$('#titleInput').value.trim()||'配信予定';schedules.push({date:selectedDate,time:selectedTime,title,genre:$('#genreInput').value});$('#titleInput').value='';renderSchedules();renderArt()}
function renderSchedules(){let box=$('#scheduleList');box.innerHTML=schedules.length?schedules.map((s,i)=>`<div class="scheduleItem"><div><b>${fmtDate(s.date)} ${s.time}</b><small>${esc(s.genre)}｜${esc(s.title)}</small></div><button onclick="delSchedule(${i})">削除</button></div>`).join(''):'<p class="hint">まだ予定がありません。まず1件追加してください。</p>'}
window.delSchedule=i=>{schedules.splice(i,1);renderSchedules();renderArt()};
function generateWithLog(){let steps=['予定数と文字量を分析しています…','はみ出さないレイアウトを計算しています…','世界観に合わせて柄を選んでいます…','配色と文字サイズを調整しています…','AI候補を作成しました！'];let i=0;$('#aiLog').textContent=steps[0];let t=setInterval(()=>{i++;$('#aiLog').textContent=steps[i]||steps.at(-1);if(i>=steps.length-1){clearInterval(t);generateCandidates(true);document.querySelector('.previewPanel').scrollIntoView({behavior:'smooth',block:'start'})}},300)}
function generateCandidates(randomize){let keys=[mood,'cool','game','minimal','cute','neon','summer','space','cafe','japan','mono','retro'];if(randomize)keys=keys.sort(()=>Math.random()-.5);let designs=keys.slice(0,8).map((k,i)=>makeDesign(k,i));$('#candidateStrip').innerHTML=designs.map((d,i)=>candidateHtml(d,i)).join('');$$('.candidate').forEach((b,i)=>b.onclick=()=>{$$('.candidate').forEach(x=>x.classList.remove('active'));b.classList.add('active');applyDesign(designs[i])});applyDesign(designs[0])}
function makeDesign(key,seed){let w=worlds[key]||worlds.pop,main=$('#mainColor')?.value||w.grad[0],accent=$('#accentColor')?.value||w.grad[1];let useCustom=seed===0;let alt=[w.grad,[main,accent],['#0f172a','#38bdf8'],['#fb7185','#fde68a'],['#4c1d95','#22d3ee'],['#064e3b','#a7f3d0'],['#1e293b','#e879f9'],['#7c2d12','#fbbf24']];let grad=useCustom?[main,accent]:alt[(seed+2)%alt.length];let pattern=w.patterns[seed%w.patterns.length];let layout=chooseLayout(seed);let score=scoreDesign(layout,pattern);return{key,name:w.name,grad,pattern,layout,score,title:w.title,font:w.font}}
function chooseLayout(seed){let n=schedules.length;if(n<=3)return ['cards','timeline','poster'][seed%3];if(n<=7)return ['timeline','cards','compact'][seed%3];if(n<=12)return ['two','timeline','compact'][seed%3];if(n<=20)return ['poster','two','compact'][seed%3];return ['mini','poster','two'][seed%3]}
function scoreDesign(layout){let n=schedules.length;let fit=(layout==='mini'||layout==='poster')?5:n<8?5:4;return{read:fit,shine:3+(Math.floor(Math.random()*3)),balance:illust.src?4:5}}
function candidateHtml(d,i){let patCss=patternCss(d.pattern);return`<button class="candidate ${i===0?'active':''}"><div class="candidateThumb" style="background:linear-gradient(135deg,${d.grad[0]},${d.grad[1]});--thumbPattern:${patCss}"><div style="position:absolute;left:12px;bottom:12px;color:#fff;font-weight:1000;text-shadow:0 2px 8px #0007;z-index:1">${d.name}</div></div><b>${d.name}案</b><div class="stars">見やすさ ${'★'.repeat(d.score.read)}${'☆'.repeat(5-d.score.read)}</div><small>${layoutName(d.layout)}・${patternName(d.pattern)}</small></button>`}
function applyDesign(d){currentDesign=d;document.documentElement.style.setProperty('--main',d.grad[0]);document.documentElement.style.setProperty('--accent',d.grad[1]);let c=$('#canvas');c.style.background=`linear-gradient(135deg,${d.grad[0]},${d.grad[1]})`;c.style.filter=`brightness(${100+brightness}%)`;$('#patternLayer').className=`patternLayer pat-${d.pattern}`;renderArt()}
function renderArt(){let d=currentDesign||makeDesign(mood,0),items=schedules.length?schedules:[{date:selectedDate,time:selectedTime,title:'配信予定を追加してね',genre:'予定'}];let n=items.length;let layout=d.layout;if(compactLevel>0){layout=compactLevel===1?'compact':compactLevel===2?'two':'mini'}let fs=calcSizes(n,layout);let art=$('#scheduleArt');art.className=`scheduleArt layout-${layout}`;let title=d.title;art.style.setProperty('--fsTitle',fs.title+'px');art.style.setProperty('--fsCard',fs.card+'px');art.style.setProperty('--fsDate',fs.date+'px');art.style.setProperty('--gap',fs.gap+'px');art.innerHTML=`<div class="artHeader"><div class="artTitle">${esc(title)}</div><div class="artSub">AI designed schedule</div></div><div class="artList">${items.map(s=>`<div class="artCard"><div class="date">${fmtDate(s.date)} ${s.time}</div><div><div class="title">${esc(s.title)}</div><div class="genre">${esc(s.genre)}</div></div></div>`).join('')}</div>`}
function calcSizes(n,layout){let base={title:34,card:19,date:13,gap:10};if(n>5){base.title=30;base.card=16;base.date=12;base.gap=8}if(n>9){base.title=26;base.card=14;base.date=11;base.gap=6}if(n>14){base.title=22;base.card=12;base.date=10;base.gap=5}if(layout==='mini'){base.title=20;base.card=11;base.date=9;base.gap=4}return base}
function loadIllust(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{illust={src:r.result,x:0,y:0,flip:false};$('#illust').src=r.result;$('#illust').style.display='block';$('#illustTools').classList.remove('hidden');$('#illustSize').value=82;$('#illustRotate').value=0;updateIllustStyle();$('#aiLog').textContent='イラストを読み込みました。ドラッグで移動できます。'};r.readAsDataURL(f)}
function updateIllustStyle(){if(!illust.src)return;let img=$('#illust'),size=$('#illustSize').value,rot=$('#illustRotate').value,flip=illust.flip?-1:1;img.style.width=size+'%';img.style.transform=`translate(${illust.x||0}px,${illust.y||0}px) rotate(${rot}deg) scaleX(${flip})`}
function autoRemoveBackground(){let img=$('#illust');if(!img.src)return;let im=new Image();im.onload=()=>{let cn=$('#workCanvas'),ctx=cn.getContext('2d');cn.width=im.width;cn.height=im.height;ctx.drawImage(im,0,0);let data=ctx.getImageData(0,0,cn.width,cn.height);let corner=avgCorners(data,cn.width,cn.height);floodRemove(data,cn.width,cn.height,corner,+$('#threshold').value,+$('#softness').value);ctx.putImageData(data,0,0);img.src=cn.toDataURL('image/png');illust.src=img.src;$('#aiLog').textContent='背景削除を適用しました。うまくいかない時は「クリック色透過」も試してください。'};im.src=img.src}
function removeColor(rgb){let img=$('#illust');if(!img.src)return;let im=new Image();im.onload=()=>{let cn=$('#workCanvas'),ctx=cn.getContext('2d');cn.width=im.width;cn.height=im.height;ctx.drawImage(im,0,0);let data=ctx.getImageData(0,0,cn.width,cn.height);removeSimilar(data,rgb,+$('#threshold').value,+$('#softness').value,false);ctx.putImageData(data,0,0);img.src=cn.toDataURL('image/png');illust.src=img.src;$('#aiLog').textContent='透過を適用しました。'};im.src=img.src}
function pickColorFromImage(e){let img=$('#illust'),rect=img.getBoundingClientRect(),im=new Image();im.onload=()=>{let cn=$('#workCanvas'),ctx=cn.getContext('2d');cn.width=im.width;cn.height=im.height;ctx.drawImage(im,0,0);let x=Math.max(0,Math.min(im.width-1,Math.floor((e.clientX-rect.left)/rect.width*im.width)));let y=Math.max(0,Math.min(im.height-1,Math.floor((e.clientY-rect.top)/rect.height*im.height)));let p=ctx.getImageData(x,y,1,1).data;pickMode=false;removeColor([p[0],p[1],p[2]])};im.src=img.src}
function avgCorners(data,w,h){let pts=[[0,0],[w-1,0],[0,h-1],[w-1,h-1]],r=0,g=0,b=0;pts.forEach(([x,y])=>{let i=(y*w+x)*4;r+=data.data[i];g+=data.data[i+1];b+=data.data[i+2]});return[r/4,g/4,b/4]}
function dist(a,r,g,b){return Math.hypot(r-a[0],g-a[1],b-a[2])}
function floodRemove(data,w,h,target,thr,soft){let q=[],seen=new Uint8Array(w*h);function push(x,y){if(x<0||y<0||x>=w||y>=h)return;let p=y*w+x;if(seen[p])return;seen[p]=1;let i=p*4;if(dist(target,data.data[i],data.data[i+1],data.data[i+2])<thr+soft)q.push(p)}for(let x=0;x<w;x++){push(x,0);push(x,h-1)}for(let y=0;y<h;y++){push(0,y);push(w-1,y)}while(q.length){let p=q.shift(),i=p*4,d=dist(target,data.data[i],data.data[i+1],data.data[i+2]);data.data[i+3]=d<thr?0:Math.min(data.data[i+3],Math.floor(255*(d-thr)/Math.max(soft,1)));let x=p%w,y=Math.floor(p/w);push(x+1,y);push(x-1,y);push(x,y+1);push(x,y-1)}}
function removeSimilar(data,target,thr,soft){for(let i=0;i<data.data.length;i+=4){let d=dist(target,data.data[i],data.data[i+1],data.data[i+2]);if(d<thr)data.data[i+3]=0;else if(soft&&d<thr+soft)data.data[i+3]=Math.floor(255*(d-thr)/soft)}}
function savePng(){let c=$('#canvas'),rect=c.getBoundingClientRect(),cn=document.createElement('canvas'),ctx=cn.getContext('2d'),scale=2;cn.width=rect.width*scale;cn.height=rect.height*scale;ctx.scale(scale,scale);let d=currentDesign||makeDesign(mood,0),gr=ctx.createLinearGradient(0,0,rect.width,rect.height);gr.addColorStop(0,d.grad[0]);gr.addColorStop(1,d.grad[1]);ctx.fillStyle=gr;roundRect(ctx,0,0,rect.width,rect.height,28,true);drawPattern(ctx,d.pattern,rect.width,rect.height);ctx.fillStyle='#fff';ctx.font='900 32px system-ui';ctx.fillText(d.title,30,58);let items=schedules.length?schedules:[{date:selectedDate,time:selectedTime,title:'配信予定',genre:''}],layout=chooseLayout(0),cols=(items.length>10||layout==='two'||layout==='poster')?2:1;let x0=30,y0=96,w=(rect.width-60-(cols-1)*10)/cols,h=Math.max(28,Math.min(58,(rect.height-150)/Math.ceil(items.length/cols)-8));items.forEach((s,i)=>{let col=i%cols,row=Math.floor(i/cols),x=x0+col*(w+10),y=y0+row*(h+8);ctx.fillStyle='rgba(255,255,255,.86)';roundRect(ctx,x,y,w,h,14,true);ctx.fillStyle=d.grad[0];ctx.font='900 11px system-ui';ctx.fillText(`${fmtDate(s.date)} ${s.time}`,x+10,y+17);ctx.fillStyle='#172033';ctx.font=`900 ${h<40?12:16}px system-ui`;ctx.fillText(s.title.slice(0,18),x+10,y+h-12)});if($('#wmCheck').checked){ctx.fillStyle='rgba(255,255,255,.75)';ctx.font='800 11px system-ui';ctx.fillText('Made with SukeDeco',rect.width-142,rect.height-18)}let a=document.createElement('a');a.href=cn.toDataURL('image/png');a.download='sukedeco_schedule.png';a.click()}
function drawPattern(ctx,p,w,h){ctx.fillStyle='rgba(255,255,255,.28)';if(p==='none')return;for(let i=0;i<110;i++){let x=Math.random()*w,y=Math.random()*h;if(['stars','dots','bubbles','confetti'].includes(p)){ctx.beginPath();ctx.arc(x,y,Math.random()*3+1,0,Math.PI*2);ctx.fill()}else if(['grid','stripe','check','hex','japan','waves','hearts'].includes(p)){ctx.fillRect(x,y,Math.random()*18+8,2)}}}
function patternCss(p){return`url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='80' height='80'%3E%3Ccircle cx='20' cy='20' r='3' fill='white' fill-opacity='.45'/%3E%3Ccircle cx='55' cy='50' r='2' fill='white' fill-opacity='.35'/%3E%3C/svg%3E")`}
function resetAll(){if(!confirm('白紙に戻しますか？'))return;schedules=[];renderSchedules();illust={src:null,x:0,y:0,flip:false};$('#illust').style.display='none';$('#illustTools').classList.add('hidden');brightness=0;compactLevel=0;generateCandidates(false)}
function fmtDate(d){if(!d)return'';let date=new Date(d+'T00:00:00');let w='日月火水木金土'[date.getDay()];return`${date.getMonth()+1}/${date.getDate()}(${w})`}function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function layoutName(l){return{cards:'カード',timeline:'時間表',compact:'コンパクト',two:'2列',poster:'ポスター',mini:'極小'}[l]||l}function patternName(p){return{stars:'星柄',hearts:'ハート',dots:'水玉',grid:'グリッド',stripe:'ストライプ',check:'チェック',waves:'波',bubbles:'泡',hex:'六角形',confetti:'紙吹雪',japan:'和柄',none:'無地'}[p]||p}
function roundRect(ctx,x,y,w,h,r,fill){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);if(fill)ctx.fill()}
init();
