const $=s=>document.querySelector(s);const events=[];let selectedDate='',selectedTime='',illustData=null,clickErase=false;
const els={mainTitle:$('#mainTitle'),eventTitle:$('#eventTitle'),dateTimeText:$('#dateTimeText'),eventsList:$('#eventsList'),canvasTitle:$('#canvasTitle'),scheduleArea:$('#scheduleArea'),canvas:$('#canvas'),patternLayer:$('#patternLayer'),illust:$('#illust'),aiMessage:$('#aiMessage')};
function pad(n){return String(n).padStart(2,'0')}function dateLabel(v){if(!v)return'';const d=new Date(v+'T00:00:00');return `${d.getMonth()+1}/${d.getDate()}(${['日','月','火','水','木','金','土'][d.getDay()]})`}
function updateDateTime(){els.dateTimeText.textContent=(selectedDate?dateLabel(selectedDate):'日付未選択')+' / '+(selectedTime||'時間未選択')}
$('#pickDateBtn').onclick=()=>{$('#datePicker').value=selectedDate||new Date().toISOString().slice(0,10);$('#dateDialog').showModal()};$('#dateOkBtn').onclick=()=>{selectedDate=$('#datePicker').value;updateDateTime();$('#dateDialog').close()};
$('#pickTimeBtn').onclick=()=>{$('#timeDialog').showModal();updateTimeView()};function updateTimeView(){$('#hourView').textContent=pad($('#hourRange').value);$('#minuteView').textContent=pad($('#minuteRange').value)}$('#hourRange').oninput=updateTimeView;$('#minuteRange').oninput=updateTimeView;$('#timeOkBtn').onclick=()=>{selectedTime=`${pad($('#hourRange').value)}:${pad($('#minuteRange').value)}`;updateDateTime();$('#timeDialog').close()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
$('#addEventBtn').onclick=()=>{const title=els.eventTitle.value.trim();if(!title){els.eventTitle.focus();return}events.push({date:selectedDate?dateLabel(selectedDate):'日付未定',time:selectedTime||'--:--',title});els.eventTitle.value='';renderEvents();renderSchedule(false)};
function renderEvents(){els.eventsList.innerHTML='';events.forEach((e,i)=>{const div=document.createElement('div');div.className='eventCard';div.innerHTML=`<div><b>${e.title}</b><br><span>${e.date} ${e.time}</span></div><button>削除</button>`;div.querySelector('button').onclick=()=>{events.splice(i,1);renderEvents();renderSchedule(false)};els.eventsList.appendChild(div)})}
function pickLayout(){const n=events.length;if(n<=0)return'empty';if(n<=4)return'normal';if(n<=8)return'compact';if(n<=14)return'two';return'mini'}function patternClass(p){return {星:'pat-star',水玉:'pat-dot',グリッド:'pat-grid',ストライプ:'pat-stripe',ハート:'pat-heart'}[p]||''}
function autoPattern(mood){const p=$('#pattern').value;if(p!=='おまかせ')return p;const map={ポップ:'水玉',クール:'グリッド',ゲーム:'グリッド',シンプル:'なし',ゆめかわ:'ハート',和風:'ストライプ',宇宙:'星'};return map[mood]||['星','水玉','グリッド','ストライプ'][events.length%4]}
function applyDesign(){const mood=$('#mood').value;const main=$('#mainColor').value;document.documentElement.style.setProperty('--main',main);let sub='#28c8ff',bg1=main,bg2='#f8fbff';if(mood==='クール'){sub='#00d4ff';bg1='#17223b';bg2='#233a66'}if(mood==='ゲーム'){sub='#00f0ff';bg1='#161a36';bg2='#4d2cff'}if(mood==='シンプル'){sub='#9aa6bd';bg1='#edf2f7';bg2='#ffffff'}if(mood==='ゆめかわ'){sub='#ff9ad5';bg1='#ffe7f6';bg2='#e8e8ff'}if(mood==='和風'){sub='#d6a441';bg1='#f8efe0';bg2='#a33b3b'}if(mood==='宇宙'){sub='#8cf2ff';bg1='#080a20';bg2='#35206c'}document.documentElement.style.setProperty('--sub',sub);els.canvas.style.background=`linear-gradient(135deg,${bg1},${bg2})`;const pat=autoPattern(mood);els.patternLayer.className='patternLayer '+patternClass(pat)}
function renderSchedule(ai=true){els.canvasTitle.textContent=els.mainTitle.value.trim()||'Schedule';applyDesign();const layout=pickLayout();els.scheduleArea.className='scheduleArea';if(layout==='empty'){els.scheduleArea.className='scheduleArea empty';els.scheduleArea.textContent='予定を追加して「スケジュールを作成」を押してください';return}els.scheduleArea.classList.add('layout-'+layout);els.scheduleArea.innerHTML='';const scale=$('#fontScale').value/100;events.forEach(e=>{const card=document.createElement('div');card.className='sCard';card.style.fontSize=`${scale}em`;card.innerHTML=`<div class="date">${e.date}</div><div class="time">${e.time}</div><div class="title">${e.title}</div>`;els.scheduleArea.appendChild(card)});if(ai){els.aiMessage.textContent=`✨ ${events.length}件の予定から「${layout==='normal'?'カード型':layout==='compact'?'コンパクト型':layout==='two'?'2列型':'極小2列型'}」で作成しました。`}}
$('#generateBtn').onclick=()=>{els.aiMessage.textContent='AIが予定数・文字量・柄を考えています…';setTimeout(()=>renderSchedule(true),450)};els.mainTitle.oninput=()=>renderSchedule(false);['mood','mainColor','pattern','fontScale'].forEach(id=>$('#'+id).oninput=()=>renderSchedule(false));
$('#watermarkToggle').onchange=e=>$('#watermark').style.display=e.target.checked?'block':'none';$('#resetBtn').onclick=()=>{if(confirm('入力内容をリセットしますか？'))location.reload()};
$('#illustInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=ev=>{illustData=ev.target.result;els.illust.src=illustData;els.illust.classList.remove('hidden')};r.readAsDataURL(f)};
function updateIllustStyle(){const s=$('#illustScale').value/100,r=$('#illustRotate').value,o=$('#illustOpacity').value/100;els.illust.style.transform=`scale(${s}) rotate(${r}deg)`;els.illust.style.opacity=o}['illustScale','illustRotate','illustOpacity'].forEach(id=>$('#'+id).oninput=updateIllustStyle);$('#deleteIllustBtn').onclick=()=>{els.illust.src='';els.illust.classList.add('hidden');illustData=null};
let drag=false,dx=0,dy=0;els.illust.addEventListener('pointerdown',e=>{drag=true;els.illust.setPointerCapture(e.pointerId);const r=els.illust.getBoundingClientRect();dx=e.clientX-r.left;dy=e.clientY-r.top});els.illust.addEventListener('pointermove',e=>{if(!drag)return;const c=els.canvas.getBoundingClientRect();els.illust.style.left=(e.clientX-c.left-dx)+'px';els.illust.style.top=(e.clientY-c.top-dy)+'px'});els.illust.addEventListener('pointerup',()=>drag=false);
function eraseBg(mode,targetColor=null){if(!els.illust.src)return;const img=new Image();img.onload=()=>{const cn=document.createElement('canvas'),ctx=cn.getContext('2d');cn.width=img.naturalWidth;cn.height=img.naturalHeight;ctx.drawImage(img,0,0);const d=ctx.getImageData(0,0,cn.width,cn.height),a=d.data;const str=Number($('#removeStrength').value);let base=targetColor;if(mode==='white')base=[255,255,255];if(mode==='auto'){const corners=[[0,0],[cn.width-1,0],[0,cn.height-1],[cn.width-1,cn.height-1]].map(([x,y])=>{const i=(y*cn.width+x)*4;return[a[i],a[i+1],a[i+2]]});base=corners.reduce((p,c)=>p.map((v,i)=>v+c[i]),[0,0,0]).map(v=>v/4)}for(let i=0;i<a.length;i+=4){const dist=Math.hypot(a[i]-base[0],a[i+1]-base[1],a[i+2]-base[2]);if(dist<str*3){a[i+3]=0}else if(dist<str*4.5){a[i+3]=Math.min(a[i+3],140)}}ctx.putImageData(d,0,0);els.illust.src=cn.toDataURL('image/png')};img.src=els.illust.src}
$('#removeWhiteBtn').onclick=()=>eraseBg('white');$('#removeClickColorBtn').onclick=()=>{clickErase=true;els.aiMessage.textContent='消したい背景色をイラスト上でクリックしてください。'};els.illust.addEventListener('click',e=>{if(!clickErase)return;clickErase=false;const img=new Image();img.onload=()=>{const cn=document.createElement('canvas'),ctx=cn.getContext('2d');cn.width=img.naturalWidth;cn.height=img.naturalHeight;ctx.drawImage(img,0,0);const r=els.illust.getBoundingClientRect();const x=Math.floor((e.clientX-r.left)/r.width*cn.width),y=Math.floor((e.clientY-r.top)/r.height*cn.height);const p=ctx.getImageData(x,y,1,1).data;eraseBg('color',[p[0],p[1],p[2]])};img.src=els.illust.src});
$('#draftBtn').onclick=()=>{localStorage.setItem('sukedecoDraft',JSON.stringify({events,title:els.mainTitle.value}));els.aiMessage.textContent='下書きを保存しました。'};
$('#savePngBtn').onclick=async()=>{const canvas=await htmlToCanvas(els.canvas);const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download='sukedeco.png';a.click()};
async function htmlToCanvas(node){const rect=node.getBoundingClientRect();const cn=document.createElement('canvas');cn.width=Math.round(rect.width*2);cn.height=Math.round(rect.height*2);const ctx=cn.getContext('2d');ctx.scale(2,2);const bg=getComputedStyle(node).backgroundImage;ctx.fillStyle='#f7f8ff';ctx.fillRect(0,0,rect.width,rect.height);ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--main')||'#7c5cff';ctx.globalAlpha=.18;for(let i=0;i<40;i++){ctx.beginPath();ctx.arc((i*47)%rect.width,(i*83)%rect.height,12,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.fillStyle='#1d2440';ctx.font='900 28px system-ui';ctx.fillText(els.canvasTitle.textContent,34,58);let y=92;const layout=pickLayout();const cols=(layout==='two'||layout==='mini')?2:1;const cardW=(rect.width-68-(cols-1)*10)/cols;events.forEach((e,i)=>{const x=34+(i%cols)*(cardW+10);if(i>0&&i%cols===0)y+=layout==='mini'?62:82;ctx.fillStyle='rgba(255,255,255,.88)';roundRect(ctx,x,y,cardW,layout==='mini'?54:72,16);ctx.fill();ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--main')||'#7c5cff';ctx.font='800 11px system-ui';ctx.fillText(e.date,x+12,y+18);ctx.fillStyle='#1d2440';ctx.font='900 16px system-ui';ctx.fillText(e.time,x+12,y+38);ctx.font='800 14px system-ui';ctx.fillText(e.title.slice(0,18),x+78,y+38)});if(!els.illust.classList.contains('hidden')){const img=new Image();img.src=els.illust.src;await img.decode().catch(()=>{});const ir=els.illust.getBoundingClientRect();ctx.globalAlpha=Number($('#illustOpacity').value)/100;ctx.drawImage(img,ir.left-rect.left,ir.top-rect.top,ir.width,ir.height);ctx.globalAlpha=1}if($('#watermarkToggle').checked){ctx.fillStyle='rgba(30,36,64,.45)';ctx.font='800 10px system-ui';ctx.fillText('Made with SukeDeco',rect.width-132,rect.height-18)}return cn}function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
updateDateTime();renderSchedule(false);
