const $ = (id) => document.getElementById(id);
const state = {
  screen:'home', step:'input', title:'今週の配信予定', events:[], mood:'pop', color:'#54a6ff', prompt:'', candidates:[], selected:0,
  illust:null, illustX:0, illustY:0, illustScale:100, illustFlip:false, watermark:true, fontScale:100
};
const moodNames = {pop:'ポップ',cool:'クール',game:'ゲーム',simple:'シンプル',cute:'かわいい',night:'夜'};
const palettes = {
  pop:['#dff4ff','#fff1f7','#54a6ff','#ff7ab6','dots'],
  cool:['#dbeafe','#eef2ff','#111827','#06b6d4','grid'],
  game:['#101827','#1e3a8a','#22d3ee','#8b5cf6','grid'],
  simple:['#f8fafc','#e2e8f0','#334155','#64748b','stripe'],
  cute:['#fff0f7','#fff7d6','#ff6fae','#f59e0b','dots'],
  night:['#1e1b4b','#312e81','#a78bfa','#22d3ee','stars']
};
const extraMoods = ['pop','cool','game','simple','cute','night'];

function showScreen(name){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(name).classList.add('active');}
function showStep(step){state.step=step;document.querySelectorAll('.step').forEach(b=>b.classList.toggle('active',b.dataset.step===step));document.querySelectorAll('.step-panel').forEach(p=>p.classList.remove('active'));$('step'+step[0].toUpperCase()+step.slice(1)).classList.add('active');}
function fmtDate(v){if(!v)return '日付'; const d=new Date(v+'T00:00:00'); const w='日月火水木金土'[d.getDay()]; return `${d.getMonth()+1}/${d.getDate()}(${w})`;}
function addEvent(){const date=$('dateInput').value; const time=$('timeInput').value; const title=$('eventTitle').value.trim(); const note=$('eventNote').value.trim(); if(!date&&!time&&!title&&!note)return; state.events.push({date,time,title:title||'配信予定',note}); $('eventTitle').value=''; $('eventNote').value=''; renderAll();}
function deleteEvent(i){state.events.splice(i,1); renderAll();}
function renderScheduleList(){const box=$('scheduleList'); box.innerHTML=''; if(state.events.length===0){box.innerHTML='<p class="hint">まだ予定がありません。まずは1件追加してください。</p>';return;} state.events.forEach((e,i)=>{const div=document.createElement('div');div.className='event-pill';div.innerHTML=`<div class="event-date">${fmtDate(e.date)}<br>${e.time||''}</div><div class="event-main"><strong>${escapeHtml(e.title)}</strong><small>${escapeHtml(e.note||'')}</small></div><button class="delete-event">削除</button>`;div.querySelector('button').onclick=()=>deleteEvent(i);box.appendChild(div);});}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
function chooseLayout(){const n=state.events.length; if(n<=3)return 'カード型'; if(n<=6)return 'リスト型'; if(n<=10)return '2列型'; return '極小2列型';}
function renderPreview(){state.title=$('mainTitle').value||'今週の配信予定'; $('previewTitle').textContent=state.title; $('previewTitle').style.fontSize = `${42*(state.fontScale/100)}px`; const badge=chooseLayout(); $('layoutBadge').textContent=badge; const ev=$('previewEvents'); ev.innerHTML=''; ev.className='preview-events'; const n=state.events.length; if(n>6) ev.classList.add('two-col'); const list=state.events.length?state.events:[{date:'',time:'',title:'予定を追加するとここに表示',note:'AIが表にします'}]; list.forEach((e)=>{const card=document.createElement('div'); card.className='schedule-card'; if(n>6) card.classList.add('compact'); if(n>10) card.classList.add('mini'); card.innerHTML=`<div class="d">${fmtDate(e.date)}<br>${e.time||''}</div><div><div class="t">${escapeHtml(e.title)}</div><div class="n">${escapeHtml(e.note||'')}</div></div>`; ev.appendChild(card);});
  $('watermark').style.display=state.watermark?'block':'none';
}
function applyTheme(mood, color){state.mood=mood||state.mood; state.color=color||state.color; const p=palettes[state.mood]||palettes.pop; const root=document.documentElement; root.style.setProperty('--primary',state.color||p[2]); root.style.setProperty('--accent',p[3]); const canvas=$('canvasPreview'); canvas.className='schedule-canvas theme-'+state.mood; canvas.style.background=`linear-gradient(135deg, ${p[0]}, ${p[1]})`; const layer=$('patternLayer'); layer.className='pattern-layer '+p[4]; const dark = ['game','night','cool'].includes(state.mood); $('previewTitle').style.color = dark ? '#fff' : '#172033'; document.querySelectorAll('.schedule-card .d').forEach(el=>el.style.color=state.color||p[2]);}
function generateCandidates(){const base=state.mood; const order=[base,...extraMoods.filter(m=>m!==base)]; state.candidates=order.slice(0,6).map((m,i)=>{const n=state.events.length; let score= n<=3?92-i*3:n<=7?88-i*2:84-i; return {mood:m,name:moodNames[m],layout:n<=3?'大きめカード':n<=6?'見やすいリスト':n<=10?'2列タイムテーブル':'情報量重視',score:Math.max(70,score),pattern:palettes[m][4]};}); state.selected=0; renderCandidates(); applyCandidate(0);}
function renderCandidates(){const list=$('candidateList'); list.innerHTML=''; state.candidates.forEach((c,i)=>{const p=palettes[c.mood]; const card=document.createElement('button'); card.className='candidate-card '+(i===state.selected?'active':''); card.innerHTML=`<div class="candidate-thumb ${p[4]}" style="background:linear-gradient(135deg,${p[0]},${p[1]})"></div><div><h3>${c.name}</h3><p>${c.layout} / ${c.pattern}</p><div class="score">見やすさ ${'★'.repeat(Math.round(c.score/20))} ${c.score}%</div></div>`; card.onclick=()=>applyCandidate(i); list.appendChild(card);});}
function applyCandidate(i){state.selected=i; const c=state.candidates[i]; if(c){applyTheme(c.mood,state.color); renderCandidates(); renderPreview();} showStep('select');}
function thinkAndGenerate(){showStep('ai'); const texts=['予定数を分析中','読みやすい配置を選択中','背景と柄を作成中','候補を6案生成中']; const box=$('thinking'); box.classList.remove('hidden'); let i=0; $('thinkingText').textContent=texts[0]; const timer=setInterval(()=>{i++; if(i<texts.length){$('thinkingText').textContent=texts[i];}else{clearInterval(timer); box.classList.add('hidden'); generateCandidates();}},520);}
function handleIllust(file){if(!file)return; const reader=new FileReader(); reader.onload=e=>{state.illust=e.target.result; $('illustImg').src=state.illust; $('illustLayer').classList.remove('hidden'); renderIllust();}; reader.readAsDataURL(file);}
function renderIllust(){const layer=$('illustLayer'); layer.style.transform=`translate(${state.illustX}px,${state.illustY}px) scale(${state.illustScale/100}) scaleX(${state.illustFlip?-1:1})`;}
function savePng(){const canvas=$('exportCanvas'); const ctx=canvas.getContext('2d'); const W=1080,H=1080; ctx.clearRect(0,0,W,H); const p=palettes[state.mood]||palettes.pop; const g=ctx.createLinearGradient(0,0,W,H); g.addColorStop(0,p[0]); g.addColorStop(1,p[1]); ctx.fillStyle=g; ctx.fillRect(0,0,W,H); drawPattern(ctx,p[4],W,H); ctx.fillStyle=['game','night','cool'].includes(state.mood)?'#fff':'#172033'; ctx.font=`900 ${Math.round(72*(state.fontScale/100))}px sans-serif`; wrapText(ctx,state.title,78,120,720,82); const n=state.events.length; const two=n>6; const cardW=two?420:690; const startX=78; let y=230; state.events.forEach((e,i)=>{const col=two?i%2:0; const row=two?Math.floor(i/2):i; const x=startX+col*(cardW+26); y=230+row*(n>10?70:92); const h=n>10?58:74; roundRect(ctx,x,y,cardW,h,24,'rgba(255,255,255,.82)'); ctx.fillStyle=state.color||p[2]; ctx.font=`900 ${n>10?20:24}px sans-serif`; ctx.fillText(fmtDate(e.date),x+20,y+30); ctx.fillText(e.time||'',x+20,y+56); ctx.fillStyle='#172033'; ctx.font=`900 ${n>10?24:30}px sans-serif`; ctx.fillText(e.title,x+145,y+32); ctx.fillStyle='#64748b'; ctx.font=`800 ${n>10?16:20}px sans-serif`; ctx.fillText(e.note||'',x+145,y+58);});
 if(state.illust){const img=$('illustImg'); const iw=330*(state.illustScale/100), ih=iw*(img.naturalHeight/img.naturalWidth||1); ctx.save(); ctx.translate(W-250+state.illustX*1.7,H-240+state.illustY*1.7); ctx.scale(state.illustFlip?-1:1,1); ctx.drawImage(img,-iw/2,-ih/2,iw,ih); ctx.restore();}
 if(state.watermark){ctx.fillStyle='rgba(15,23,42,.42)';ctx.font='900 22px sans-serif';ctx.fillText('Made with SukeDeco',W-270,H-36);} const a=document.createElement('a'); a.download='sukedeco_schedule.png'; a.href=canvas.toDataURL('image/png'); a.click();}
function drawPattern(ctx,type,W,H){ctx.save(); if(type==='dots'){ctx.fillStyle='rgba(255,255,255,.42)'; for(let x=0;x<W;x+=42)for(let y=0;y<H;y+=42){ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill();}} if(type==='grid'){ctx.strokeStyle='rgba(255,255,255,.2)';ctx.lineWidth=2;for(let x=0;x<W;x+=52){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();}for(let y=0;y<H;y+=52){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}} if(type==='stripe'){ctx.fillStyle='rgba(255,255,255,.18)'; for(let x=-W;x<W*2;x+=54){ctx.save();ctx.translate(x,0);ctx.rotate(-Math.PI/4);ctx.fillRect(0,0,20,H*2);ctx.restore();}} if(type==='stars'){ctx.fillStyle='rgba(255,255,255,.65)';ctx.font='36px sans-serif';for(let i=0;i<35;i++){ctx.fillText(i%2?'✧':'✦',Math.random()*W,Math.random()*H);}} ctx.restore();}
function roundRect(ctx,x,y,w,h,r,fill){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();ctx.fillStyle=fill;ctx.fill();}
function wrapText(ctx,text,x,y,maxWidth,lineHeight){let words=String(text).split('');let line='';for(const ch of words){let test=line+ch;if(ctx.measureText(test).width>maxWidth){ctx.fillText(line,x,y);line=ch;y+=lineHeight;}else line=test;}ctx.fillText(line,x,y);}
function renderAll(){renderScheduleList(); renderPreview(); applyTheme(state.mood,state.color); localStorage.setItem('sukedeco_v2',JSON.stringify({title:state.title,events:state.events,mood:state.mood,color:state.color}));}
function load(){try{const s=JSON.parse(localStorage.getItem('sukedeco_v2')||'{}'); if(s.events)state.events=s.events; if(s.title)$('mainTitle').value=s.title; if(s.mood)state.mood=s.mood; if(s.color)state.color=s.color;}catch(e){} const today=new Date(); $('dateInput').value=today.toISOString().slice(0,10); renderAll();}

document.addEventListener('DOMContentLoaded',()=>{
 $('startBtn').onclick=()=>{showScreen('create');showStep('input');}; $('resetBtn').onclick=()=>{localStorage.removeItem('sukedeco_v2'); location.reload();};
 document.querySelectorAll('.step').forEach(b=>b.onclick=()=>showStep(b.dataset.step));
 $('addEventBtn').onclick=addEvent; $('toAiBtn').onclick=()=>showStep('ai'); $('generateBtn').onclick=thinkAndGenerate; $('moreBtn').onclick=generateCandidates; $('saveBtn').onclick=savePng;
 $('mainTitle').oninput=renderPreview; $('fontSizeRange').oninput=e=>{state.fontScale=+e.target.value; renderPreview();}; $('illustScaleRange').oninput=e=>{state.illustScale=+e.target.value; renderIllust();}; $('flipIllust').onchange=e=>{state.illustFlip=e.target.checked; renderIllust();}; $('watermarkToggle').onchange=e=>{state.watermark=e.target.checked; renderPreview();}; $('illustInput').onchange=e=>handleIllust(e.target.files[0]);
 document.querySelectorAll('#moodGroup .chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('#moodGroup .chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mood=b.dataset.mood;applyTheme(state.mood,state.color);});
 document.querySelectorAll('#colorGroup .color-dot').forEach(b=>b.onclick=()=>{document.querySelectorAll('#colorGroup .color-dot').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.color=b.dataset.color;applyTheme(state.mood,state.color);});
 let drag=false,sx=0,sy=0,ox=0,oy=0; const layer=$('illustLayer'); layer.addEventListener('pointerdown',e=>{drag=true;sx=e.clientX;sy=e.clientY;ox=state.illustX;oy=state.illustY;layer.setPointerCapture(e.pointerId);}); layer.addEventListener('pointermove',e=>{if(!drag)return; state.illustX=ox+(e.clientX-sx); state.illustY=oy+(e.clientY-sy); renderIllust();}); layer.addEventListener('pointerup',()=>drag=false);
 load();
});
